## 0D Tensor

In [1]:
import numpy as np

In [2]:
a = np.array(4)

In [3]:
a

array(4)

In [4]:
a.ndim

0

In [5]:
a.shape

()

## 1D Tensor

Sometimes number of dimensions = rank of tensor = number of axes

In [6]:
arr = np.array([1, 2, 3, 4])

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
arr.ndim

1

### vector dimension of [1, 2, 3, 4] is 4

## 2D Tensor/Matrice

In [9]:
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [10]:
mat

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
mat.ndim

2

In [12]:
mat[0]

array([1, 2, 3, 4])

In [15]:
mat[0].ndim

1

## Shape

It is the maximum number of numbers you can contain in an axis/dimension

In [16]:
mat.shape

(2, 4)

In [17]:
mat.ndim

2

## Size 
just how many numbers it stores

In [18]:
mat.size

8